name: CI

on: [push, pull_request]

jobs:
  lab0-c:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.4.0
    - name: install-dependencies
      run: |
            .ci/check-sanity.sh
            sudo apt-get update
            sudo apt-get -q -y install build-essential cppcheck
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make test
      run: make test

  coding-style:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.4.0
    - name: coding convention
      run: |
            sudo apt-get install -q -y clang-format-12
            sh .ci/check-format.sh
      shell: bash
